// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Database_crud_p.Models
{
    public partial class Department
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }
}